# Generated by Django 5.0.3 on 2024-03-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attractions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=300)),
                ("img_link", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
