# Generated by Django 5.0.3 on 2024-04-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebSite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attractions",
            name="nearest_node",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
