# Generated by Django 5.0.3 on 2024-03-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebSite", "0002_userroute"),
    ]

    operations = [
        migrations.AddField(
            model_name="userroute",
            name="coordinates_list",
            field=models.TextField(default=None, null=True),
        ),
    ]
