# Generated by Django 5.0.3 on 2024-03-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WebSite", "0003_userroute_coordinates_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("gmail", models.CharField(max_length=50)),
                ("theme", models.CharField(max_length=100)),
                ("mes", models.TextField()),
            ],
        ),
    ]
